USE QLTT;

INSERT INTO NguoiDung(UserID,Username,Email,Password,hashSalt,Status,Role) VALUES
(1,'admin','22520771@gm.uit.edu.vn','admin@123','0','Verified',1);

-- Insert dữ liệu vào bảng UserAlertType
INSERT INTO UserAlertType(alert_type_id, alert_description) VALUES
(1, N'Temperature'),
(2, N'Humidity'),
(3, N'UV'),
(4, N'Feels like'),
(5, N'Air quality index'),
(6, N'Visibility'),
(7, N'Clouds');

-- Insert dữ liệu vào bảng WeatherCondition
INSERT INTO WeatherCondition (weather_condition_id, main, weather_description) VALUES
(200, 'Thunderstorm', 'thunderstorm with light rain'),
(201, 'Thunderstorm', 'thunderstorm with rain'),
(202, 'Thunderstorm', 'thunderstorm with heavy rain'),
(210, 'Thunderstorm', 'light thunderstorm'),
(211, 'Thunderstorm', 'thunderstorm'),
(212, 'Thunderstorm', 'heavy thunderstorm'),
(221, 'Thunderstorm', 'ragged thunderstorm'),
(230, 'Thunderstorm', 'thunderstorm with light drizzle'),
(231, 'Thunderstorm', 'thunderstorm with drizzle'),
(232, 'Thunderstorm', 'thunderstorm with heavy drizzle'),
(300, 'Drizzle', 'light intensity drizzle'),
(301, 'Drizzle', 'drizzle'),
(302, 'Drizzle', 'heavy intensity drizzle'),
(310, 'Drizzle', 'light intensity drizzle rain'),
(311, 'Drizzle', 'drizzle rain'),
(312, 'Drizzle', 'heavy intensity drizzle rain'),
(313, 'Drizzle', 'shower rain and drizzle'),
(314, 'Drizzle', 'heavy shower rain and drizzle'),
(321, 'Drizzle', 'shower drizzle'),
(500, 'Rain', 'light rain'),
(501, 'Rain', 'moderate rain'),
(502, 'Rain', 'heavy intensity rain'),
(503, 'Rain', 'very heavy rain'),
(504, 'Rain', 'extreme rain'),
(511, 'Rain', 'freezing rain'),
(520, 'Rain', 'light intensity shower rain'),
(521, 'Rain', 'shower rain'),
(522, 'Rain', 'heavy intensity shower rain'),
(531, 'Rain', 'ragged shower rain'),
(600, 'Snow', 'light snow'),
(601, 'Snow', 'snow'),
(602, 'Snow', 'heavy snow'),
(611, 'Snow', 'sleet'),
(612, 'Snow', 'light shower sleet'),
(613, 'Snow', 'shower sleet'),
(615, 'Snow', 'light rain and snow'),
(616, 'Snow', 'rain and snow'),
(620, 'Snow', 'light shower snow'),
(621, 'Snow', 'shower snow'),
(622, 'Snow', 'heavy shower snow'),
(701, 'Mist', 'mist'),
(711, 'Smoke', 'smoke'),
(721, 'Haze', 'haze'),
(731, 'Dust', 'sand/dust whirls'),
(741, 'Fog', 'fog'),
(751, 'Sand', 'sand'),
(761, 'Dust', 'dust'),
(762, 'Ash', 'volcanic ash'),
(771, 'Squall', 'squalls'),
(781, 'Tornado', 'tornado'),
(800, 'Clear', 'clear sky'),
(801, 'Clouds', 'few clouds: 11-25%'),
(802, 'Clouds', 'scattered clouds: 25-50%'),
(803, 'Clouds', 'broken clouds: 51-84%'),
(804, 'Clouds', 'overcast clouds: 85-100%');



-- Insert dữ liệu vào bảng Country
INSERT INTO Country (country_id, country_name) VALUES
('ABW', N'Aruba'),
('AFG', N'Afghanistan'),
('AGO', N'Angola'),
('AIA', N'Anguilla'),
('ALB', N'Albania'),
('AND', N'Andorra'),
('ARE', N'United Arab Emirates'),
('ARG', N'Argentina'),
('ARM', N'Armenia'),
('ASM', N'American Samoa'),
('ATG', N'Antigua and Barbuda'),
('AUS', N'Australia'),
('AUT', N'Austria'),
('AZE', N'Azerbaijan'),
('BDI', N'Burundi'),
('BEL', N'Belgium'),
('BEN', N'Benin'),
('BES', N'Bonaire, Sint Eustatius, and Saba'),
('BFA', N'Burkina Faso'),
('BGD', N'Bangladesh'),
('BGR', N'Bulgaria'),
('BHR', N'Bahrain'),
('BHS', N'Bahamas, The'),
('BIH', N'Bosnia and Herzegovina'),
('BLM', N'Saint Barthelemy'),
('BLR', N'Belarus'),
('BLZ', N'Belize'),
('BMU', N'Bermuda'),
('BOL', N'Bolivia'),
('BRA', N'Brazil'),
('BRB', N'Barbados'),
('BRN', N'Brunei'),
('BTN', N'Bhutan'),
('BWA', N'Botswana'),
('CAF', N'Central African Republic'),
('CAN', N'Canada'),
('CHE', N'Switzerland'),
('CHL', N'Chile'),
('CHN', N'China'),
('CIV', N'Cote d’Ivoire'),
('CMR', N'Cameroon'),
('COD', N'Congo (Kinshasa)'),
('COG', N'Congo (Brazzaville)'),
('COK', N'Cook Islands'),
('COL', N'Colombia'),
('COM', N'Comoros'),
('CPV', N'Cabo Verde'),
('CRI', N'Costa Rica'),
('CUB', N'Cuba'),
('CUW', N'Curaçao'),
('CXR', N'Christmas Island'),
('CYM', N'Cayman Islands'),
('CYP', N'Cyprus'),
('CZE', N'Czechia'),
('DEU', N'Germany'),
('DJI', N'Djibouti'),
('DMA', N'Dominica'),
('DNK', N'Denmark'),
('DOM', N'Dominican Republic'),
('DZA', N'Algeria'),
('ECU', N'Ecuador'),
('EGY', N'Egypt'),
('ERI', N'Eritrea'),
('ESP', N'Spain'),
('EST', N'Estonia'),
('ETH', N'Ethiopia'),
('FIN', N'Finland'),
('FJI', N'Fiji'),
('FLK', N'Falkland Islands'),
('FRA', N'France'),
('FRO', N'Faroe Islands'),
('FSM', N'Federated States of Micronesia'),
('GAB', N'Gabon'),
('GBR', N'United Kingdom'),
('GEO', N'Georgia'),
('GGY', N'Guernsey'),
('GHA', N'Ghana'),
('GIB', N'Gibraltar'),
('GIN', N'Guinea'),
('GLP', N'Guadeloupe'),
('GMB', N'Gambia, The'),
('GNB', N'Guinea-Bissau'),
('GNQ', N'Equatorial Guinea'),
('GRC', N'Greece'),
('GRD', N'Grenada'),
('GRL', N'Greenland'),
('GTM', N'Guatemala'),
('GUF', N'French Guiana'),
('GUM', N'Guam'),
('GUY', N'Guyana'),
('HKG', N'Hong Kong'),
('HND', N'Honduras'),
('HRV', N'Croatia'),
('HTI', N'Haiti'),
('HUN', N'Hungary'),
('IDN', N'Indonesia'),
('IMN', N'Isle of Man'),
('IND', N'India'),
('IRL', N'Ireland'),
('IRN', N'Iran'),
('IRQ', N'Iraq'),
('ISL', N'Iceland'),
('ISR', N'Israel'),
('ITA', N'Italy'),
('JAM', N'Jamaica'),
('JEY', N'Jersey'),
('JOR', N'Jordan'),
('JPN', N'Japan'),
('KAZ', N'Kazakhstan'),
('KEN', N'Kenya'),
('KGZ', N'Kyrgyzstan'),
('KHM', N'Cambodia'),
('KIR', N'Kiribati'),
('KNA', N'Saint Kitts and Nevis'),
('KOR', N'Korea, South'),
('KWT', N'Kuwait'),
('LAO', N'Laos'),
('LBN', N'Lebanon'),
('LBR', N'Liberia'),
('LBY', N'Libya'),
('LCA', N'Saint Lucia'),
('LIE', N'Liechtenstein'),
('LKA', N'Sri Lanka'),
('LSO', N'Lesotho'),
('LTU', N'Lithuania'),
('LUX', N'Luxembourg'),
('LVA', N'Latvia'),
('MAC', N'Macau'),
('MAF', N'Saint Martin'),
('MAR', N'Morocco'),
('MCO', N'Monaco'),
('MDA', N'Moldova'),
('MDG', N'Madagascar'),
('MDV', N'Maldives'),
('MEX', N'Mexico'),
('MHL', N'Marshall Islands'),
('MKD', N'North Macedonia'),
('MLI', N'Mali'),
('MLT', N'Malta'),
('MMR', N'Myanmar'),
('MNE', N'Montenegro'),
('MNG', N'Mongolia'),
('MNP', N'Northern Mariana Islands'),
('MOZ', N'Mozambique'),
('MRT', N'Mauritania'),
('MSR', N'Montserrat'),
('MTQ', N'Martinique'),
('MUS', N'Mauritius'),
('MWI', N'Malawi'),
('MYS', N'Malaysia'),
('MYT', N'Mayotte'),
('NAM', N'Namibia'),
('NCL', N'New Caledonia'),
('NER', N'Niger'),
('NFK', N'Norfolk Island'),
('NGA', N'Nigeria'),
('NIC', N'Nicaragua'),
('NIU', N'Niue'),
('NLD', N'Netherlands'),
('NOR', N'Norway'),
('NPL', N'Nepal'),
('NRU', N'Nauru'),
('NZL', N'New Zealand'),
('OMN', N'Oman'),
('PAK', N'Pakistan'),
('PAN', N'Panama'),
('PCN', N'Pitcairn Islands'),
('PER', N'Peru'),
('PHL', N'Philippines'),
('PLW', N'Palau'),
('PNG', N'Papua New Guinea'),
('POL', N'Poland'),
('PRI', N'Puerto Rico'),
('PRK', N'Korea, North'),
('PRT', N'Portugal'),
('PRY', N'Paraguay'),
('PYF', N'French Polynesia'),
('QAT', N'Qatar'),
('REU', N'Reunion'),
('ROU', N'Romania'),
('RUS', N'Russia'),
('RWA', N'Rwanda'),
('SAU', N'Saudi Arabia'),
('SDN', N'Sudan'),
('SEN', N'Senegal'),
('SGP', N'Singapore'),
('SGS', N'South Georgia and South Sandwich Islands'),
('SHN', N'Saint Helena, Ascension, and Tristan da Cunha'),
('SLB', N'Solomon Islands'),
('SLE', N'Sierra Leone'),
('SLV', N'El Salvador'),
('SMR', N'San Marino'),
('SOM', N'Somalia'),
('SPM', N'Saint Pierre and Miquelon'),
('SRB', N'Serbia'),
('SSD', N'South Sudan'),
('STP', N'Sao Tome and Principe'),
('SUR', N'Suriname'),
('SVK', N'Slovakia'),
('SVN', N'Slovenia'),
('SWE', N'Sweden'),
('SWZ', N'Eswatini'),
('SXM', N'Sint Maarten'),
('SYC', N'Seychelles'),
('SYR', N'Syria'),
('TCA', N'Turks and Caicos Islands'),
('TCD', N'Chad'),
('TGO', N'Togo'),
('THA', N'Thailand'),
('TJK', N'Tajikistan'),
('TKM', N'Turkmenistan'),
('TLS', N'Timor-Leste'),
('TON', N'Tonga'),
('TTO', N'Trinidad and Tobago'),
('TUN', N'Tunisia'),
('TUR', N'Turkey'),
('TUV', N'Tuvalu'),
('TWN', N'Taiwan'),
('TZA', N'Tanzania'),
('UGA', N'Uganda'),
('UKR', N'Ukraine'),
('URY', N'Uruguay'),
('USA', N'United States'),
('UZB', N'Uzbekistan'),
('VAT', N'Vatican City'),
('VCT', N'Saint Vincent and the Grenadines'),
('VEN', N'Venezuela'),
('VGB', N'Virgin Islands, British'),
('VIR', N'U.S. Virgin Islands'),
('VNM', N'Vietnam'),
('VUT', N'Vanuatu'),
('WLF', N'Wallis and Futuna'),
('WSM', N'Samoa'),
('XGZ', N'Gaza Strip'),
('XKS', N'Kosovo'),
('XSV', N'Svalbard'),
('XWB', N'West Bank'),
('YEM', N'Yemen'),
('ZAF', N'South Africa'),
('ZMB', N'Zambia'),
('ZWE', N'Zimbabwe');



-- Insert dữ liệu từ file CSV vào bảng City
-- Lệnh này chỉ hoạt động nếu bạn có quyền truy cập file hệ thống từ MySQL
LOAD DATA INFILE 'E:/Documents (D)/Daigaku/UIT/IE103/CK/city.csv'
INTO TABLE City
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;